"""Generate the report's tables from a results directory (so every number is read from a saved file).

Usage:
    python scripts/report_tables.py results/<exp_id> [--out report/tables.md]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import pandas as pd

LABEL = {"iris": "Iris", "digits": "Digits", "heart_cleveland": "Heart Disease"}
METHOD = {"baseline": "Default RF", "random_search": "Random search", "pso": "PSO"}


def _cfg(record: dict) -> str:
    c = record["best_hyperparameters"]
    depth = "None" if c["max_depth"] is None else c["max_depth"]
    return f"({c['n_estimators']}, {depth}, {c['min_samples_split']})"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("results", type=Path)
    parser.add_argument("--out", type=Path, default=Path("report/tables.md"))
    args = parser.parse_args(argv)
    root = args.results
    summary = pd.read_csv(root / "summary.csv")
    folds = pd.read_csv(root / "summary_folds.csv")
    manifest = json.loads((root / "manifest.json").read_text(encoding="utf-8"))
    lines = [
        f"<!-- generated by scripts/report_tables.py from {root.as_posix()}; do not edit by hand -->",
        "",
    ]

    lines += [
        "### T1 · Datasets (source: `<dataset>/audit.json`)",
        "",
        "| Dataset | Samples | Features | Classes | Class counts | Max/min ratio | Missing cells | Fitness metric |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for ds in LABEL:
        a = json.loads((root / ds / "audit.json").read_text(encoding="utf-8"))
        missing = sum(a["missing_per_feature"].values())
        counts = " / ".join(str(v) for v in a["class_counts"].values())
        lines.append(
            f"| {LABEL[ds]} | {a['n_samples']} | {a['n_features']} | {a['n_classes']} | {counts} | "
            f"{a['class_ratio']:.2f} | {missing} | {a['fitness_metric']} |"
        )

    lines += [
        "",
        "### T2 · Main results, 5 outer folds (source: `summary.csv`)",
        "",
        "| Dataset | Method | Test accuracy (mean ± sd) | Test macro F1 | Δ acc vs default (mean ± sd) | "
        "W/T/L vs default | W/T/L vs random search | Validation acc. (biased) | Unique RF fits (mean) |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for row in summary.itertuples():
        delta = (
            "–"
            if row.method == "baseline"
            else f"{row.delta_accuracy_mean:+.4f} ± {row.delta_accuracy_std:.4f}"
        )
        wtl = "–" if pd.isna(row.wins) else f"{int(row.wins)}/{int(row.ties)}/{int(row.losses)}"
        rs = (
            "–"
            if pd.isna(row.wins_vs_rs)
            else f"{int(row.wins_vs_rs)}/{int(row.ties_vs_rs)}/{int(row.losses_vs_rs)}"
        )
        lines.append(
            f"| {LABEL[row.dataset]} | {METHOD[row.method]} | {row.test_accuracy_mean:.4f} ± "
            f"{row.test_accuracy_std:.4f} | {row.test_f1_macro_mean:.4f} | {delta} | {wtl} | {rs} | "
            f"{row.validation_fitness_mean:.4f} | {row.n_unique_fits_mean:.1f} |"
        )

    lines += [
        "",
        "### T3 · Chosen configurations per outer fold, (n_estimators, max_depth, min_samples_split) "
        "(source: `<dataset>/fold_<k>/<method>/final.json`)",
        "",
        "| Dataset | Fold | Random search | PSO | PSO ties with best | PSO on a bound | PSO convergence iteration |",
        "|---|---|---|---|---|---|---|",
    ]
    for ds in LABEL:
        for k in sorted(folds[folds.dataset == ds].outer_fold.unique()):
            rs = json.loads(
                (root / ds / f"fold_{k}" / "random_search" / "final.json").read_text(encoding="utf-8")
            )
            pso = json.loads((root / ds / f"fold_{k}" / "pso" / "final.json").read_text(encoding="utf-8"))
            bounds = ", ".join(pso["boundary_hits"]) or "–"
            lines.append(
                f"| {LABEL[ds]} | {k} | {_cfg(rs)} | {_cfg(pso)} | {pso['n_ties_with_best']} | {bounds} | "
                f"{pso['convergence_iteration']} |"
            )

    lines += [
        "",
        "### T5 · Deployment runs (source: `<dataset>/deployment/pso/deployment.json`)",
        "",
        "| Dataset | Recommended configuration | Outer-CV performance estimate (test accuracy) |",
        "|---|---|---|",
    ]
    for ds in LABEL:
        d = json.loads((root / ds / "deployment" / "pso" / "deployment.json").read_text(encoding="utf-8"))
        c, e = d["recommended_hyperparameters"], d["performance_estimate"]
        lines.append(
            f"| {LABEL[ds]} | ({c['n_estimators']}, {c['max_depth']}, {c['min_samples_split']}) | "
            f"{e['test_accuracy_mean']:.4f} ± {e['test_accuracy_std']:.4f} |"
        )

    lines += [
        "",
        "### T6 · Runtime and provenance (source: `manifest.json`, `summary.csv`)",
        "",
        "| Item | Value |",
        "|---|---|",
        f"| Experiment | `{manifest['exp_id']}` |",
        f"| Git commit | `{manifest['git_commit'][:12]}` (dirty: {manifest['git_dirty']}) |",
        f"| Config hash | `{manifest['config_hash'][:16]}` |",
        f"| Started / finished (UTC) | {manifest['created_at']} / {manifest['finished_at']} |",
        f"| Platform | {manifest['platform']}, {manifest['cpu_count']} CPUs, Python {manifest['python_version']} |",
    ]
    for ds in LABEL:
        seconds = summary[summary.dataset == ds].total_time_s_sum.sum()
        lines.append(f"| Fold runs, {LABEL[ds]} | {seconds / 60:.1f} min |")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
